### ISSUE TITLE
Dist

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gunzenroses/slider-plugin#1]
Не стоит хранить собранный проект (dist) в репозитории.

**Comment by gunzenroses** [comment]
> Не стоит хранить собранный проект (dist) в репозитории.

Папку удалила, но можно ли узнать почему это плохая практика?)

**Comment by ArsenGadjiusmanov** [comment]
> > Не стоит хранить собранный проект (dist) в репозитории.
> 
> Папку удалила, но можно ли узнать почему это плохая практика?)

Ну готовую сборку можно получить из исходников. Еще тебе необходимо следить затем чтобы сборка всегда была обновлена если что-то поменялось. А еще это все отображается в твоем гите где вместе с комитами с исправлениями будут и просто сборки. 
Для сборок обычно делают отдельную ветку и туда все заливают) gh-pages у тебя она вроде уже есть
