### ISSUE TITLE
Presenter

### ISSUE THREAD

**Issue by Geksanit** [gunzenroses/slider-plugin#10]
![image](https://user-images.githubusercontent.com/31949379/175026133-8b6034fa-6d93-4cf8-a87b-ec17466ac2fc.png)
1. зачем нужно поле `data`, если везде достаточно только `this.model.getData()`?
2. почему model/view не приватные поля? для общения с внешним миром достаточно getData() и modelData()
3. `modelData` лучше переимновать в что-то похожее на `setData` или `updateData`, `updateModel` ...
4. зачем вообще нужен `updateView`? если он публичный, то можно изменить вью не меняя модель, зачем?

**Comment by gunzenroses** [comment]
Наконец-то исправила!:-)

**Comment by gunzenroses** [comment]
@Geksanit, привет! наконец исправила:-)
