### ISSUE TITLE
Observer

### ISSUE THREAD

**Issue by ArsenGadjiusmanov** [gunzenroses/slider-plugin#4]
Старые слушатели событий не удаляются 
![image](https://user-images.githubusercontent.com/89850975/154849537-b2fcc358-2e8a-43c2-acdc-8d13feed4f30.png)

**Comment by ArsenGadjiusmanov** [comment]
![image](https://user-images.githubusercontent.com/89850975/154851113-cb512a7b-2d59-45df-98c4-26224a47fe60.png)
Здесь подписчики получают весь View, это не безопасно так как кто угодно из них сможет его изменить

**Comment by gunzenroses** [comment]
> Старые слушатели событий не удаляются

Можешь объяснить как можно обнаружить этот массив? Не могу понять что конкретно работает не так.

**Comment by ArsenGadjiusmanov** [comment]
> > Старые слушатели событий не удаляются
> 
> Можешь объяснить как можно обнаружить этот массив? Не могу понять что конкретно работает не так.
![image](https://user-images.githubusercontent.com/89850975/154998232-a46d4784-6baa-476e-bef2-f92d634ad904.png)

Добавил консоль для того, чтобы посмотреть какие слушатели висят на view
