### ISSUE TITLE
Обсервер

### ISSUE THREAD

**Issue by osyka-yuri** [gunzenroses/slider-plugin#6]
Сейчас экземпляр обсервера создается в свойстве класса, что не очень правильно, так как при таком подходе мы не можем ограничить видимость методов и свойств, в данном случае метод notify не должен быть виден снаружи. Более правильным было бы использовать наследование, и у нас появится возможно сделать свойство или метод protected, и оно не будет доступно снаружи, но при этом оно будет доступно классам наследникам. Еще если класс обсервера будет использоваться только для наследования то его стоит сделать абстрактным.

Так же сейчас неизвестно какие события вообще доступны и какие данные будут переданны при том или ином событии. Чтобы это исправить можно использовать generic аргумент. К примеру:
```
type Listener<T> = <K extends keyof T>(args: T[K]) => void;

type Listeners<T> = Record<keyof T, Listener<T>[]>;

class Observable<T extends Record<string, unknown>> {
  private listeners: Listeners<T> = {} as Listeners<T>;

  add<K extends keyof T>(eventKey: K, listener: Listener<T>): void {
    if (this.listeners[eventKey]) {
      this.listeners[eventKey].push(listener);
    } else {
      this.listeners[eventKey] = [listener];
    }
  }

  protected notify<K extends keyof T>(eventKey: K, args: T[K]): void {
    if (this.listeners[eventKey]) {
      this.listeners[eventKey].forEach((listener) => listener(args));
    }
  }

  delete<K extends keyof T>(eventKey: K, listener: Listener<T>): void {
    if (!listener) {
      delete this.listeners[eventKey];
    }
    if (listener) {
      const index = this.listeners[eventKey].indexOf(listener);
      if (index !== -1) {
        this.listeners[eventKey].splice(index, 1);
      }
      const lengthOfListeners = this.listeners[eventKey].length;
      if (lengthOfListeners === 0) {
        delete this.listeners[eventKey];
      }
    }
  }
}

export default Observable;

```

В данном примере в качестве generic аргумента нужно передавать тип объекта в котором ключи будут названиями событий, а их значениями тип данных, к примеру:

```
type ModelEvents = {
  "valueUpdate": number;
}
```

---

https://github.com/gunzenroses/slider-plugin/blob/18713a4052a373767993c56a6cb1d1ac488ac70a/src/components/Observable/Observable.ts#L21-L23
Для каких целей может понадобиться удаление свойства? Просто как мне кажется это может быть несколько опасно, так при его удалении все обработчики перестанут работать. Если действительно нужен такой функционал, то его стоит вынести в отдельный метод.

**Comment by gunzenroses** [comment]
> Для каких целей может понадобиться удаление свойства?

Когда View отрисовывается заново, чтобы убрать подписанные на изменения subViews. Иначе будет

**Comment by gunzenroses** [comment]
> Для каких целей может понадобиться удаление свойства?

Когда View отрисовывается заново, нужно убрать все подписанные на изменения предыдущего View SubViews (которых у меня 3, но теоретически могут быть добавлены ещё). 
Если не удалять, то количество подписанных SubView будет расти (за счет сохранения SubViews от предыдущих View), тормозить процессы и засорять память.

**Comment by osyka-yuri** [comment]
> > Для каких целей может понадобиться удаление свойства?
> 
> Когда View отрисовывается заново, нужно убрать все подписанные на изменения предыдущего View SubViews (которых у меня 3, но теоретически могут быть добавлены ещё). Если не удалять, то количество подписанных SubView будет расти (за счет сохранения SubViews от предыдущих View), тормозить процессы и засорять память.

Тут  несколько некорректная логика, зачем subviews подписываться на событие view? Тут должно быть наоборот view должен быть подписан на события subviews если это необходимо, дочерние элементы не должны знать о родительском, если subview нужно обновить, то можно для этого создать соответствующий метод  в нем, а в view его уже будет вызывать по необходимости.

---

Сейчас все еще не понятно какие события могут происходить) то есть при вызове методов notifiy или addListener мы сейчас можешь передать не существующее событие и любые данные. Если что-то не понятно спрашивай.

---

https://github.com/gunzenroses/slider-plugin/blob/837a40ea08c620fb0538eac5017ba87b29ec805b/src/components/Observable/Observable.ts#L23
Тут необязательность второго аргумента может где-то и пригодится, но сейчас это используется несколько странно.
https://github.com/gunzenroses/slider-plugin/blob/837a40ea08c620fb0538eac5017ba87b29ec805b/src/components/Model/Model.ts#L76
Вместо того чтобы сразу передать текущее состояние, в перезентер дополнительно вызывает метод getData чтобы их получить.

**Comment by osyka-yuri** [comment]
https://github.com/gunzenroses/slider-plugin/blob/837a40ea08c620fb0538eac5017ba87b29ec805b/src/components/Observable/Observable.ts#L30
Вот это не очень хорошо, сейчас получается обсервер, знает об окружении.

**Comment by gunzenroses** [comment]
> Если что-то не понятно спрашивай.

Применила предлагаемую типизацию для Observable:-)

Далее был задан тип для событий в Presenter.
![image](https://user-images.githubusercontent.com/60935997/164969268-e76fe80e-8566-4f49-ab17-201add5d7a91.png) 

Из **type Listener<T> = <K extends keyof T>(args: T[K]) => void** предполагается, что слушатели Презентера имеют тип Listeners: (args: number | TSettings) => void.

Из-за чего выдается ошибка: **Argument of type '(data: TSettings) => void' is not assignable to parameter of type 'Listener<TPresenterObservable>**. Более конкретно: Type 'number | TSettings' is not assignable to type 'number'. 

Как можно преодолеть возникшую проблему? Логически, тип аргументов должен определяться по ключу из списка TPresenterObservable, но фактически этого не происходит.

**Comment by osyka-yuri** [comment]
> > Если что-то не понятно спрашивай.
> 
> Применила предлагаемую типизацию для Observable:-)
> 
> Далее был задан тип для событий в Presenter. ![image](https://user-images.githubusercontent.com/60935997/164969268-e76fe80e-8566-4f49-ab17-201add5d7a91.png)
> 
> Из **type Listener = (args: T[K]) => void** предполагается, что слушатели Презентера имеют тип Listeners: (args: number | TSettings) => void.
> 
> Из-за чего выдается ошибка: **Argument of type '(data: TSettings) => void' is not assignable to parameter of type 'Listener**. Более конкретно: Type 'number | TSettings' is not assignable to type 'number'.
> 
> Как можно преодолеть возникшую проблему? Логически, тип аргументов должен определяться по ключу из списка TPresenterObservable, но фактически этого не происходит.

Да, я допустил ошибку при определении типов для слушателя, из-за чего возникла проблема с тем что передаваемый тип события не связан со значением первого аргумента метода, в итоге он обозначал все ключи. Чтобы решить данную проблему, нужно исправить тип слушателя на `type TListener<T> = (args: T) => void;` и передавать ему уже тип T[K] `TListener<T[K]>`, а вот для типизации массива слушателей стоит применить mapped type, чтобы корректно определить типы аргументов слушателя `type TListenerArr<T> = {
  [K in keyof T]: TListener<T[K]>[];
};`
Итоговый вариант обсервера:
```
abstract class Observable<T extends Record<string, unknown>> {
  listeners: TListenerArr<T> = {} as TListenerArr<T>;

  addListener<K extends keyof T>(eventKey: K, listener: TListener<T[K]>): void {
    if (this.listeners[eventKey]) {
      this.listeners[eventKey].push(listener);
    } else {
      this.listeners[eventKey] = [listener];
    }
  }

  deleteListener<K extends keyof T>(eventKey: K, listener: TListener<T[K]>): void {
    if (listener) {
      const index = this.listeners[eventKey].indexOf(listener);
      if (index !== -1) {
        this.listeners[eventKey].splice(index, 1);
      }
    }
  }

  protected notifyListener<K extends keyof T>(eventKey: K, args: T[K]): void {
    if (this.listeners[eventKey]) {
      this.listeners[eventKey].forEach((listener) => listener(args));
    }
  }
}

export default Observable;
```
